FROM node:20
RUN npm install -g  \
    aws-cdk \
    neovim \
    tree-sitter-bash  \
    tree-sitter-cli \
    tree-sitter-css  \
    https://github.com/camdencheek/tree-sitter-dockerfile \
    https://github.com/MichaHoffmann/tree-sitter-hcl \
    tree-sitter-html  \
    tree-sitter-javascript  \
    tree-sitter-json  \
    https://github.com/PowerShell/tree-sitter-PowerShell \
    tree-sitter-python \
    tree-sitter-regex  \
    tree-sitter-rust \
    tree-sitter-toml  \
    tree-sitter-yaml
