FROM python:3.11
RUN python -m pip install --upgrade pip && python -m pip install pynvim \
  ansible-lint \
  yamllint black \
  flake8 \
  gitlint \
  debugpy \
  python-lsp-server[all] \
  yamlfix \
  yamllint